name: homework_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/hero.png
    - assets/images/dishes/Cappuccino.png
    - assets/images/dishes/Croissant.png
    - assets/images/dishes/Espresso.png
    - assets/images/dishes/lemontart.png
    - assets/images/dishes/Latte.png
    - assets/images/dishes/Mocha.png
    - assets/images/dishes/IcedCoffee.png
    - assets/images/dishes/BlueberryMuffin.png
    - assets/images/dishes/AvocadoToast.png
    - assets/images/dishes/TunaSandwich.png
    - assets/images/dishes/ChickenSandwich.png


